### ISSUE TITLE
实在抱歉：打扰下  请问 llama-3.1-8b,    报错：AttributeError: 'OmniSpeechLlamaForCausalLM' object has no attribute 'initialize_speech_generator'

### ISSUE THREAD

**Issue by SevenMpp** [wntg/LLaMA-Omni#2]
您好，打扰下，像尝试下您的方式，目前使用的是原生的meta-llama-3.1-8b-instruct，包如下错误，请问是因为config 修改的问题？？？
因看 builder.py 中的 model_cls = OmniSpeech2SLlamaForCausalLM if s2s else OmniSpeechLlamaForCausalLM导致的OmniSpeech2SLlamaForCausalLM 中包含initialize_speech_generator 但是 OmniSpeechLlamaForCausalLM中不包含。请问这两个初始化有什么不同吗？
## config.json 配置
![image](https://github.com/user-attachments/assets/28c315b0-25dc-4270-8512-1c53b3bc4754)

##版本
torch 2.3.0
transformers 4.43.4

启动命令：
#!/bin/bash

ROOT=$1

VOCODER_CKPT=vocoder/g_00500000
VOCODER_CFG=vocoder/config.json

python omni_speech/train/stage1.py \
    --model-path meta-llama-3.1-8b-instruct \
    --question-file data.json \
    --answer-file answer.json \
    --num-chunks 1 \
    --chunk-idx 0 \
    --temperature 0 \
    --conv-mode llama_3 \
    --input_type mel \
    --mel_size 128 \

错误信息
File "/llama-omni-reproduction/omni_speech/train/stage1.py", line 164, in <module>
    train_model(args)
  File "/llama-omni-reproduction/omni_speech/train/stage1.py", line 100, in train_model
    tokenizer, model, context_len = create_model(model_path, args.model_base, is_lora=args.is_lora, s2s=args.s2s)
  File "/llama-omni-reproduction/omni_speech/model/builder.py", line 145, in create_model
    model.initialize_speech_generator(model.config)
  File "/home/ls/anaconda3/envs/llama-omni-train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OmniSpeechLlamaForCausalLM' object has no attribute 'initialize_speech_generator'

**Comment by WWWWxp** [comment]
我也遇到了这个问题

**Comment by huanglong123** [comment]
一阶段应该是注释掉model.initialize_speech_generator(model.config)就行了

**Comment by SevenMpp** [comment]
> 一阶段应该是注释掉model.initialize_speech_generator(model.config)就行了

好的  非常感谢您的回复

**Comment by wntg** [comment]
感谢帮忙回复，确实是这样，model.initialize_speech_generator(model.config)是第二阶段用的
