### ISSUE TITLE
您好，打扰下 关于库版本问题

### ISSUE THREAD

**Issue by SevenMpp** [wntg/LLaMA-Omni#6]
transformers             4.43.4
tokenizers               0.19.1
torch                    2.1.2
torchaudio               2.1.2
torchvision              0.16.2
按照llama-omni安装，推理没问题，但是训练，这是目前几个主要得库和版本，请问您训练的相关版本是多少？？？
![image](https://github.com/user-attachments/assets/d97a4a34-5643-48b4-82af-158967cd697a)

**Comment by SevenMpp** [comment]
后续 更新了joblib 的版本由1.4.2降到1.1.1，但是出现新问题错误
![image](https://github.com/user-attachments/assets/889673fa-f039-4996-ad33-003e2ae4ab23)
![image](https://github.com/user-attachments/assets/ad7ad456-b9cb-4e3c-bde6-2c9adab47ff6)

**Comment by wntg** [comment]
absl-py                   2.1.0
accelerate                0.33.0
aiofiles                  23.2.1
annotated-types           0.7.0
antlr4-python3-runtime    4.8
anyio                     4.5.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bitarray                  2.9.2
bitsandbytes              0.43.1
black                     22.3.0
bleach                    6.1.0
blessed                   1.20.0
certifi                   2024.8.30
cffi                      1.17.1
chardet                   3.0.4
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
comm                      0.2.2
contourpy                 1.3.0
cycler                    0.12.1
Cython                    3.0.11
debugpy                   1.8.7
decorator                 5.1.1
defusedxml                0.7.1
dill                      0.3.8
docopt                    0.6.2
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.2
executing                 2.1.0
fastapi                   0.112.4
fastjsonschema            2.20.0
ffmpy                     0.4.0
filelock                  3.16.1
fire                      0.7.0
flake8                    5.0.4
flash-attn                2.6.3
flatbuffers               24.3.25
fonttools                 4.53.1
fqdn                      1.5.1
fsspec                    2024.9.0
googletrans               4.0.0rc1
gpustat                   1.1.1
gradio                    4.43.0
gradio_client             1.3.0
grpcio                    1.66.1
h11                       0.9.0
h2                        3.2.0
hpack                     3.0.0
hstspreload               2024.11.1
httpcore                  0.9.1
httpx                     0.13.3
huggingface-hub           0.25.0
humanfriendly             10.0
hydra-core                1.0.7
hyperframe                5.2.0
idna                      2.10
importlib_resources       6.4.5
ipdb                      0.13.13
ipykernel                 6.29.5
ipython                   8.27.0
ipywidgets                8.1.5
isoduration               20.11.0
isort                     5.10.1
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter                   1.1.1
jupyter_client            8.6.3
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.13
kaldi-decoder             0.2.7
kaldialign                0.9.1
kaldifst                  1.7.12
kaldilm                   1.15.1
kiwisolver                1.4.7
latex2mathml              3.77.0
llama-omni                1.0.0         project/LLaMA-Omni
llvmlite                  0.43.0
lxml                      5.3.0
Markdown                  3.7
markdown-it-py            3.0.0
markdown2                 2.5.0
MarkupSafe                2.1.5
matplotlib                3.9.2
matplotlib-inline         0.1.7
mccabe                    0.7.0
mdurl                     0.1.2
mistune                   3.0.2
more-itertools            10.5.0
mpmath                    1.3.0
mypy-extensions           1.0.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.3
notebook                  7.2.2
notebook_shim             0.2.4
num2words                 0.5.13
numba                     0.60.0
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-ml-py              12.560.30
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.6.68
nvidia-nvtx-cu12          12.1.105
omegaconf                 2.0.6
onnx                      1.16.2
onnxconverter-common      1.14.0
onnxoptimizer             0.3.13
onnxruntime               1.19.2
onnxsim                   0.4.36
openai-whisper            20231117
orjson                    3.10.7
overrides                 7.7.0
packaging                 24.1
pandas                    2.2.2
pandocfilters             1.5.1
parso                     0.8.4
pathspec                  0.12.1
peft                      0.3.0
pexpect                   4.9.0
pillow                    10.4.0
pip                       24.0
platformdirs              4.3.6
portalocker               2.10.1
prometheus_client         0.21.0
prompt_toolkit            3.0.47
protobuf                  3.20.2
psutil                    6.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pycantonese               3.4.0
pycodestyle               2.9.1
pycparser                 2.22
pydantic                  2.9.2
pydantic_core             2.23.4
pydub                     0.25.1
pyflakes                  2.5.0
Pygments                  2.18.0
pylangacq                 0.16.2
pyparsing                 3.1.4
pypinyin                  0.50.0
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
python-multipart          0.0.9
pytz                      2024.2
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.35.1
regex                     2024.9.11
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986                   1.5.0
rfc3986-validator         0.1.1
rich                      13.8.1
rpds-py                   0.20.0
ruff                      0.6.5
sacrebleu                 2.4.3
safetensors               0.4.5
scikit-learn              1.2.2
scipy                     1.14.1
semantic-version          2.10.0
Send2Trash                1.8.3
sentencepiece             0.1.99
setuptools                59.5.0
shellingham               1.5.4
shortuuid                 1.0.13
six                       1.16.0
sniffio                   1.3.1
soundfile                 0.12.1
soupsieve                 2.6
stack-data                0.6.3
starlette                 0.38.5
svgwrite                  1.4.3
sympy                     1.13.3
tabulate                  0.9.0
tensorboard               2.17.1
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
termcolor                 2.5.0
terminado                 0.18.1
threadpoolctl             3.5.0
tiktoken                  0.7.0
timm                      0.6.13
tinycss2                  1.4.0
tokenizers                0.19.1
tomli                     2.0.1
tomlkit                   0.12.0
torch                     2.1.2
torchaudio                2.1.2
torchvision               0.16.2
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
transformers              4.43.4
triton                    2.1.0
typeguard                 4.3.0
typer                     0.12.5
types-python-dateutil     2.9.0.20241003
typing_extensions         4.12.2
tzdata                    2024.1
uri-template              1.3.0
urllib3                   2.2.3
uvicorn                   0.30.6
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                12.0
Werkzeug                  3.0.4
wheel                     0.44.0
widgetsnbextension        4.0.13
wordseg                   0.0.2

**Comment by wntg** [comment]
joblib                           1.4.2
transformers              4.43.4
torch                           2.1.2
torchaudio                 2.1.2
torchvision                 0.16.2
tokenizers                0.19.1
我核对了一下，和你是一致的

**Comment by SevenMpp** [comment]
> joblib 1.4.2 transformers 4.43.4 torch 2.1.2 torchaudio 2.1.2 torchvision 0.16.2 tokenizers 0.19.1 我核对了一下，和你是一致的

非常感谢您的回复，joblib 的版本由1.4.2降到1.1.1，因显卡比较旧，因此我使用 了 fp16，可能因为它导致的，再输入的时候不符，导致再 
speech_permuted = speech.permute(0, 2, 1)
encoder_outs = speech_encoder(speech_permuted)
这里出现问题，我再解决看看

**Comment by wntg** [comment]
fp16可能会有另一个问题，训练的时候loss会为nan，主要跟whisper的norm有关，在另一个项目中发生过https://github.com/modelscope/ms-swift/issues/1653

**Comment by SevenMpp** [comment]
> fp16可能会有另一个问题，训练的时候loss会为nan，主要跟whisper的norm有关，在另一个项目中发生过[modelscope/ms-swift#1653](https://github.com/modelscope/ms-swift/issues/1653)

嗯 我看到input_ids 里面 还存在了 -200 这样的值 是很异常的。嗯 我看看如何解决把，或者我换个新一些的GPU，如果两张3090，共48G  训练1B 的这个模型 是不是空间也足够啦

**Comment by wntg** [comment]
是的，1B模型有24G就够了
