### ISSUE TITLE
再次打扰：输入的标量（0 维张量）进行收集（gather）操作。

### ISSUE THREAD

**Issue by SevenMpp** [wntg/LLaMA-Omni#7]
求教！！！ 虽然不影响运行，但是出现warning，再并行处理时，不知是否是数据不当导致的？ 

Warning 信息如下：
warning: /python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
 warnings.warn('Was asked to gather along dimension 0, but all '

**Comment by wntg** [comment]
具体是哪行报的

**Comment by wu-wen-zhou** [comment]
当我运行pip install flash-attn --no-build-isolation这条命令时，会报下面的错误，
Collecting flash-attn
  Using cached flash_attn-2.7.2.post1.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 156, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 82, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'


      torch.__version__  = 2.1.2+cu121


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

我并没有找到/usr/local/cuda/bin/nvcc这个路径，我应该怎么解决这个问题。求教

**Comment by SevenMpp** [comment]
> 具体是哪行报的
是再训练阶段：
trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        args=training_args,
        train_dataset=data_loader,
        eval_dataset=data_loader,
        data_collator=collate_fn
    )
    trainer.train()
torch.nn.parallel.DataParallel 的 gather 函数中触发的。具体来说，问题发生在多 GPU 训练过程中尝试收集来自不同设备的输出时，当这些输出是标量时，PyTorch 无法沿指定维度进行收集，因此触发了警告。
![image](https://github.com/user-attachments/assets/8f47db64-944c-425c-b124-01f3272f0a52)

我查到的原因：


    损失函数配置：
        如果你在计算损失时直接返回了一个标量值（例如通过 .mean() 或 .sum()），那么在多 GPU 环境中尝试收集这些标量会导致警告。

    模型输出配置：
        某些情况下，模型的最后一层可能会返回一个标量值而不是预期的张量。例如，如果你在模型的最后一层使用了 nn.Linear 并且之后调用了 .mean() 或其他聚合操作。

    数据加载器或 collate 函数：
        如果 collate_fn 或者 data_loader 返回的数据格式不正确，可能会导致模型输出不符合预期。

    评估指标配置：
        如果你在评估阶段计算某些标量指标（如准确率、损失等），并且这些指标没有被正确地包装成张量，也可能导致标量输出。

我再改改看看，您有时间也可以看看！！！

**Comment by wntg** [comment]
> 当我运行pip install flash-attn --no-build-isolation这条命令时，会报下面的错误， Collecting flash-attn Using cached flash_attn-2.7.2.post1.tar.gz (3.1 MB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [22 lines of output] fatal: not a git repository (or any of the parent directories): .git Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 156, in _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME) File "/tmp/pip-install-j7xyhe9c/flash-attn_d871209e23f84ff78b283e03c2e57230/setup.py", line 82, in get_cuda_bare_metal_version raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True) File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 421, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/root/miniconda3/envs/llama-omni/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'
> 
> ```
>   torch.__version__  = 2.1.2+cu121
> 
> 
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> 我并没有找到/usr/local/cuda/bin/nvcc这个路径，我应该怎么解决这个问题。求教

你这个是cuda环境的问题，正常装好cuda都是有个路径的，你ls看下/usr/local/ 有没有别的cuda版本

**Comment by wntg** [comment]
应该是发生在collate_fn函数里，这里会把每张的数据放到一起padding，存在gather操作，这里可以打印确认下，是不是有维度异常

**Comment by SevenMpp** [comment]
> 应该是发生在collate_fn函数里，这里会把每张的数据放到一起padding，存在gather操作，这里可以打印确认下，是不是有维度异常
非常感谢您多次的回复，万分感谢，修改了模型的前向传播中的loss，消除了异常，可以正常跑，看后续训练完，会不会有影响。
![image](https://github.com/user-attachments/assets/fbd244a7-a5cb-4a20-82e1-6d838956f3c9)

![image](https://github.com/user-attachments/assets/c8f2b9d3-6f9d-4f3e-b133-cfb9188552bd)
